# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-24 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liighter_app', '0002_auto_20170624_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
